apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  labels:
    app: mario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario
        image: pengbai/docker-supermario
---
apiVersion: v1
kind: Service
metadata:
  name: mario
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nplb"  # NPLB 설정 (네트워크 프록시 로드 밸런서)
    service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL"  # 로드 밸런서 성능을 SMALL로 설정
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "false"  # 외부에서 접근 가능하도록 설정
spec:
  type: LoadBalancer
  selector:
    app: mario
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
