apiVersion: apps/v1
kind: Deployment
metadata:
  name: quake
spec:
  selector:
    matchLabels:
      run: quake
  replicas: 1  # Pod의 복제본 수, 여기서는 하나의 서버만 실행
  template:
    metadata:
      labels:
        run: quake
      annotations:
        prometheus.io/scrape: 'true'  # Prometheus가 모니터링할 수 있도록 설정
        prometheus.io/port: '8080'    # Prometheus가 수집할 포트 번호 지정
    spec:
      containers:
      - command:
        - q3
        - server
        - --config=/config/config.yaml  # 서버 설정 파일 위치
        - --content-server=http://127.0.0.1:9090  # 컨텐츠 서버 주소 설정
        - --agree-eula  # EULA(최종 사용자 라이선스 동의서) 동의 옵션
        image: docker.io/criticalstack/quake:latest  # Quake 서버 Docker 이미지
        name: server
        ports:
        - containerPort: 8080  # 클라이언트가 연결할 서버 포트
        readinessProbe:
          tcpSocket:
            port: 8080  # 서버의 준비 상태를 확인할 포트
          initialDelaySeconds: 15  # 서버 시작 후 상태 확인 대기 시간
          periodSeconds: 5  # 상태 확인 주기
        volumeMounts:
        - name: quake3-server-config
          mountPath: /config  # 설정 파일을 마운트할 경로
        - name: quake3-content
          mountPath: /assets  # 게임 컨텐츠를 마운트할 경로
      - command:
        - q3
        - content
        - --seed-content-url=http://content.quakejs.com  # 컨텐츠 다운로드 URL 설정
        image: docker.io/criticalstack/quake:latest  # Quake 컨텐츠 서버 Docker 이미지
        name: content-server
        ports:
        - containerPort: 9090  # 컨텐츠 서버가 동작할 포트
        volumeMounts:
        - name: quake3-content
          mountPath: /assets  # 컨텐츠 저장 경로
      volumes:
        - name: quake3-server-config
          configMap:
            name: quake3-server-config  # 서버 설정을 저장한 ConfigMap 참조
        - name: quake3-content
          emptyDir: {}  # 비어 있는 디렉토리로 컨텐츠를 임시 저장
---
apiVersion: v1
kind: Service
metadata:
  name: quake
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nplb"  # NPLB 설정 (네트워크 프록시 로드 밸런서)
    service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL"  # 로드 밸런서 성능을 SMALL로 설정
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "false"  # 외부에서 접근 가능하도록 설정
spec:
  type: LoadBalancer  # 외부 IP를 제공하여 외부 접속이 가능하도록 설정
  selector:
    run: quake  # Deployment의 레이블을 기준으로 Pod을 선택
  ports:
    - port: 8080  # 외부에서 접근할 클라이언트 포트
      targetPort: 8080  # 컨테이너 내부의 포트
      name: client
      protocol: TCP
    - port: 27960  # 게임 서버가 사용하는 포트
      targetPort: 27960
      name: server
      protocol: TCP
    - port: 9090  # 컨텐츠 서버 포트
      targetPort: 9090
      name: content
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quake3-server-config
data:
  config.yaml: |  # 서버 설정 파일 내용
    fragLimit: 25  # 한 게임에서 제한되는 프래그 수
    timeLimit: 15m  # 한 게임의 시간 제한
    bot:
      minPlayers: 3  # 최소 플레이어 수
    game:
      motd: "Welcome to Critical Stack"  # 서버에 접속 시 표시될 메시지
      type: FreeForAll  # 게임 타입 설정
      forceRespawn: false  # 강제 리스폰 설정
      inactivity: 10m  # 비활동 상태 타임아웃 시간
      quadFactor: 3  # Quad 데미지 배수 설정
      weaponRespawn: 3  # 무기 리스폰 시간
    server:
      hostname: "quakekube"  # 서버 호스트 이름 설정
      maxClients: 12  # 최대 접속 가능한 클라이언트 수
      password: "changeme"  # 서버 접속 패스워드
    commands:
      - addbot sarge 2  # 서버 시작 시 봇 추가 명령
    maps:
    - name: q3dm7
      type: FreeForAll
      timeLimit: 10m
    - name: q3dm17
      type: FreeForAll
    - name: q3wctf1
      type: CaptureTheFlag
      captureLimit: 8
    - name: q3tourney2
      type: Tournament
    - name: q3wctf3
      type: CaptureTheFlag
      captureLimit: 8
    - name: ztn3tourney1
      type: Tournament`
